#pragma once
//MACIEJ GORALCZYK 193302
//EDIT AS WISH BELOW
#define SCORE_MULTIPLIER 0.1
#define SCORE_TRESHOLD 10

#define SPEED_MULTIPLIER 100
#define DEFAULT_SPEED 3
#define FAST_SPEED 2*DEFAULT_SPEED
#define SLOW_SPEED 0.3*DEFAULT_SPEED
#define HORIZONTAL_SPEED_MULTIPLIER 150
#define DEFAULT_HORIZONTAL_SPEED 1

#define STARTING_CARS 3
#define TIME_THRESHOLD 10
#define SCORE_AWARD_KILL 60
#define SCORE_PENALTY_CIVILIANS 100

#define DEFAULT_BULLET_SPEED 2
#define SPECIAL_BULLET_SPEED_MULTIPLIER 3
#define AMMO_INFO_SIZE 20
#define AMMO_INFO_OFFSET 20

#define SIDE_COLLISION 0.75
#define ENEMY_STRENGTH 7
#define KILL_INFO_TIME 200

#define SCORE_PER_NEW_CAR 1500
#define SHOOT_DEBUG_MODE 0 // When is equal to 1, gives info to the console when enemies are hit

//menu
#define MENU_X 10
#define MENU_Y 10
#define MENU_H 55
#define MENU_PADDING 10

//friend
#define FRIEND_DEFAULT_X 161+CAR_WIDTH/2
#define FRIEND_DEFAULT_Y SCREEN_HEIGHT+1+CAR_HEIGHT/2
#define FRIEND_SPEED 1.25

//enemy1
#define ENEMY_1_DEFAULT_X 369+CAR_WIDTH/2
#define ENEMY_1_DEFAULT_Y SCREEN_HEIGHT+1+CAR_HEIGHT/2
#define ENEMY_1_SPEED 1.35

//enemy2
#define ENEMY_2_DEFAULT_X 320
#define ENEMY_2_DEFAULT_Y 4*SCREEN_HEIGHT+1+CAR_HEIGHT/2
#define ENEMY_2_SPEED 0.85

//powerup
#define POWER_UP_Y 1800
#define POWER_UP_RANDOM_OFFSET 100
#define POWER_UP_AMMO_BONUS 2


//DO NOT EDIT BELOW
#define WINDOW_TITLE "Maciej Goralczyk 193302"
#define GRASS_AREAS_COUNT 7
#define ENEMIES_COUNT 2
#define SURFACES_COUNT 9

#define CAR_WIDTH 40
#define CAR_HEIGHT 50
#define BULLET_HEIGHT 20
#define BULLET_WIDTH 10
#define POWER_UP_SIZE 30

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define TILE_WIDTH SCREEN_WIDTH/16
#define MAP_HEIGHT SCREEN_HEIGHT*7
#define MAP_TILES SCREEN_HEIGHT*6

#define TEXT_BUFFER_LENGTH 128
#define CHARACTER_WIDTH 8
#define ARROW_UP_CHAR "\030"
#define ARROW_DOWN_CHAR "\031"
#define ARROW_LEFT_CHAR "\032"
#define ARROW_RIGHT_CHAR "\033"
#define FUNCTIONALITIES_WIDTH 5
#define SPACE_PER_FUNCTIONALITY CHARACTER_WIDTH*4
#define FUNC_MENU_H 5 * MENU_PADDING
#define FUNC_MENU_W FUNCTIONALITIES_WIDTH*SPACE_PER_FUNCTIONALITY
#define FUNC_MENU_X SCREEN_WIDTH-FUNC_MENU_W
#define FUNC_MENU_Y SCREEN_HEIGHT - FUNC_MENU_H
#define PAUSE_INFO_SIZE 100

#define SAFE_POSITION_X 240
